Add problem matchers to GA

diff --git a/.github/workflows/lint_cc.yaml b/.github/workflows/lint_cc.yaml
--- a/.github/workflows/lint_cc.yaml
+++ b/.github/workflows/lint_cc.yaml
@@ -28,9 +28,13 @@ jobs:
         uses: actions/checkout@v3
         with:
           submodules: recursive
+          fetch-depth: 2
+      - name: Mark the GitHub workspace as a safe Git directory
+        run: |
+          git config --global --add safe.directory "$GITHUB_WORKSPACE"
       - name: Set up the Python virtual environment
         run: |
-          python3.8 -m venv ~/venv-lint
+          python3.10 -m venv ~/venv-lint
 
           echo ~/venv-lint/bin >> "$GITHUB_PATH"
       - name: Install PyTorch
@@ -48,11 +52,17 @@ jobs:
           export CUDAFLAGS="--allow-unsupported-compiler"
 
           CC=clang CXX=clang++ cmake -GNinja -DCMAKE_BUILD_TYPE=Release -B build
-#      - name: Run clang-format
-#        if: success() || (failure() && steps.setup.outcome == 'success')
-#        run: |
-#          tools/linters/run-clang-format --dry-run .
+      - name: Run clang-format
+        if: success() || (failure() && steps.setup.outcome == 'success')
+        run: |
+          if ! git clang-format --diff HEAD^; then
+            echo "::warning::clang-format has reported one or more formatting errors." && exit 1
+          fi
       - name: Run clang-tidy
         if: success() || (failure() && steps.setup.outcome == 'success')
         run: |
+          echo "::add-matcher::./ci/problem-matchers/gcc.json"
+
           run-clang-tidy -p build -config="{InheritParentConfig: true, WarningsAsErrors: '*'}" -quiet
+
+          echo "::remove-matcher owner=gcc::"
