Refactor C++ code base to fairseq2n

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -4,14 +4,14 @@
 # This source code is licensed under the BSD-style license found in the
 # LICENSE file in the root directory of this source tree.
 
-name: Release
-
-run-name: Relase (${{ inputs.release_type || 'nightly' }})
+run-name: ${{ inputs.release_type }}
 
 on:
-  # At 1:15AM UTC on every Monday.
-  schedule:
-    - cron: '15 1 * * 1'
+  workflow_call:
+    inputs:
+      release_type:
+        type: string
+        required: true
   workflow_dispatch:
     inputs:
       release_type:
@@ -23,226 +23,50 @@ on:
           - 'stable'
 
 jobs:
-  lint_cc:
-    name: Lint C++
-    uses: ./.github/workflows/lint_cc.yaml
+  set_version:
+    outputs:
+      version: ${{ steps.set_version.outputs.version }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check-out the repository
+        uses: actions/checkout@v3
+      - name: Set version
+        id: set_version
+        env:
+          RELEASE_TYPE: ${{ inputs.release_type }}
+        run: |
+          version=$(cat VERSION)
 
-  lint_py:
-    name: Lint Python
-    uses: ./.github/workflows/lint_py.yaml
+          if [[ $RELEASE_TYPE == nightly ]]; then
+            version=${version%+devel}.dev$(date +%Y%m%d)
+          else
+            if [[ $version == *+* ]]; then
+              echo "A PEP 440 version with a local label cannot be released as 'stable' or 'rc'." >&2
 
-  lint_sh:
-    name: Lint shell scripts
-    uses: ./.github/workflows/lint_sh.yaml
+              exit 1
+            fi
+          fi
+
+          echo version=$version >> "$GITHUB_OUTPUT"
 
   build_doc:
-    name: Build documentation
-    uses: ./.github/workflows/build_doc.yaml
-
-  build_wheel-linux-x86_64:
-    name: Build wheel (pt${{matrix.torch}}, py${{ matrix.py}}, linux_x86_64, ${{ matrix.variant }}, ${{ matrix.sanitizers }})
-    needs: [lint_cc, lint_py, lint_sh]
-    uses: ./.github/workflows/build_wheel-linux.yaml
-    strategy:
-      matrix:
-        include:
-          # PT 1.12.1
-          - torch: '1.12.1'  # CPU
-            py: '3.8'
-            variant: 'cpu'
-            sanitizers: 'nosan'
-          - torch: '1.12.1'
-            py: '3.9'
-            variant: 'cpu'
-            sanitizers: 'nosan'
-          - torch: '1.12.1'
-            py: '3.10'
-            variant: 'cpu'
-            sanitizers: 'nosan'
-
-          - torch: '1.12.1'  # CUDA 11.6
-            py: '3.8'
-            variant: 'cu116'
-            sanitizers: 'nosan'
-          - torch: '1.12.1'
-            py: '3.9'
-            variant: 'cu116'
-            sanitizers: 'nosan'
-          - torch: '1.12.1'
-            py: '3.10'
-            variant: 'cu116'
-            sanitizers: 'nosan'
-
-          # PT 1.13.1
-          - torch: '1.13.1'  # CPU
-            py: '3.8'
-            variant: 'cpu'
-            sanitizers: 'nosan'
-          - torch: '1.13.1'
-            py: '3.9'
-            variant: 'cpu'
-            sanitizers: 'nosan'
-          - torch: '1.13.1'
-            py: '3.10'
-            variant: 'cpu'
-            sanitizers: 'nosan'
-
-          - torch: '1.13.1'  # CUDA 11.6
-            py: '3.8'
-            variant: 'cu116'
-            sanitizers: 'nosan'
-          - torch: '1.13.1'
-            py: '3.9'
-            variant: 'cu116'
-            sanitizers: 'nosan'
-          - torch: '1.13.1'
-            py: '3.10'
-            variant: 'cu116'
-            sanitizers: 'nosan'
-
-          # PT 2.0.1
-          - torch: '2.0.1'   # CPU
-            py: '3.8'
-            variant: 'cpu'
-            sanitizers: 'nosan'
-          - torch: '2.0.1'
-            py: '3.9'
-            variant: 'cpu'
-            sanitizers: 'nosan'
-          - torch: '2.0.1'
-            py: '3.10'
-            variant: 'cpu'
-            sanitizers: 'nosan'
-
-          - torch: '2.0.1'   # CUDA 11.7
-            py: '3.8'
-            variant: 'cu117'
-            sanitizers: 'nosan'
-          - torch: '2.0.1'
-            py: '3.9'
-            variant: 'cu117'
-            sanitizers: 'nosan'
-          - torch: '2.0.1'
-            py: '3.10'
-            variant: 'cu117'
-            sanitizers: 'nosan'
-
-          - torch: '2.0.1'   # CUDA 11.8
-            py: '3.8'
-            variant: 'cu118'
-            sanitizers: 'nosan'
-          - torch: '2.0.1'
-            py: '3.9'
-            variant: 'cu118'
-            sanitizers: 'nosan'
-          - torch: '2.0.1'
-            py: '3.10'
-            variant: 'cu118'
-            sanitizers: 'nosan'
-
-          - torch: '2.0.1'   # ASAN_UBSAN
-            py: '3.10'
-            variant: 'cpu'
-            sanitizers: 'asan_ubsan'
+    needs: set_version
+    uses: ./.github/workflows/_build_doc.yaml
     with:
-      torch: ${{ matrix.torch }}
-      py: ${{ matrix.py }}
-      arch: 'x86_64'
-      variant: ${{ matrix.variant }}
-      sanitizers: ${{ matrix.sanitizers }}
+      version: ${{ needs.set_version.outputs.version }}
 
-  publish_linux-x86_64:
-    name: Publish wheel (pt${{ matrix.torch }}, py${{ matrix.py }}, linux_${{ matrix.arch }}, ${{ matrix.variant }})
-    needs: [build_doc, build_wheel-linux-x86_64]
-    strategy:
-      max-parallel: 1
-      matrix:
-        include:
-          # PT 1.12.1
-          - torch: '1.12.1'  # CPU
-            py: '3.8'
-            variant: 'cpu'
-          - torch: '1.12.1'
-            py: '3.9'
-            variant: 'cpu'
-          - torch: '1.12.1'
-            py: '3.10'
-            variant: 'cpu'
+  lint:
+    uses: ./.github/workflows/_lint.yaml
 
-          - torch: '1.12.1'  # CUDA 11.6
-            py: '3.8'
-            variant: 'cu116'
-          - torch: '1.12.1'
-            py: '3.9'
-            variant: 'cu116'
-          - torch: '1.12.1'
-            py: '3.10'
-            variant: 'cu116'
-
-          # PT 1.13.1
-          - torch: '1.13.1'  # CPU
-            py: '3.8'
-            variant: 'cpu'
-          - torch: '1.13.1'
-            py: '3.9'
-            variant: 'cpu'
-          - torch: '1.13.1'
-            py: '3.10'
-            variant: 'cpu'
-
-          - torch: '1.13.1'  # CUDA 11.6
-            py: '3.8'
-            variant: 'cu116'
-          - torch: '1.13.1'
-            py: '3.9'
-            variant: 'cu116'
-          - torch: '1.13.1'
-            py: '3.10'
-            variant: 'cu116'
-
-          # PT 2.0.1
-          - torch: '2.0.1'   # CPU
-            py: '3.8'
-            variant: 'cpu'
-          - torch: '2.0.1'
-            py: '3.9'
-            variant: 'cpu'
-          - torch: '2.0.1'
-            py: '3.10'
-            variant: 'cpu'
-
-          - torch: '2.0.1'   # CUDA 11.7
-            py: '3.8'
-            variant: 'cu117'
-          - torch: '2.0.1'
-            py: '3.9'
-            variant: 'cu117'
-          - torch: '2.0.1'
-            py: '3.10'
-            variant: 'cu117'
-
-          - torch: '2.0.1'   # CUDA 11.8
-            py: '3.8'
-            variant: 'cu118'
-            sanitizers: 'nosan'
-          - torch: '2.0.1'
-            py: '3.9'
-            variant: 'cu118'
-          - torch: '2.0.1'
-            py: '3.10'
-            variant: 'cu118'
-    uses: ./.github/workflows/publish_wheel.yaml
+  build:
+    needs: [set_version, lint]
+    uses: ./.github/workflows/_build.yaml
     with:
-      os: 'linux'
-      torch: ${{ matrix.torch }}
-      py: ${{ matrix.py }}
-      arch: 'x86_64'
-      variant: ${{ matrix.variant }}
-      release_type: ${{ inputs.release_type || 'nightly' }}
+      version: ${{ needs.set_version.outputs.version }}
 
-  publish_doc:
-    name: Publish documentation
-    needs: [build_doc, build_wheel-linux-x86_64]
-    uses: ./.github/workflows/publish_doc.yaml
+  publish:
+    needs: [set_version, build, build_doc]
+    uses: ./.github/workflows/_publish.yaml
     with:
-      nightly: ${{ github.event_name == 'schedule' || inputs.release_type == 'nightly' }}
+      version: ${{ needs.set_version.outputs.version }}
+      release_type: ${{ inputs.release_type }}
